### INPUT

# ckpt_path     : out/reproduce__NAN/model_255000.pth
# ckpt_path     : /home/chan/MetaNAN/out/nan_unet_resnet18_init_lambda0.5__NAN/model_030000.pth
ckpt_path     : /disk1/chanho/3d/MetaNAN/out/nan_plain__NAN/model_060000.pth
# ckpt_path     : /disk1/chanho/3d/MetaNAN/out/nan_resUnet_ae_meta_annealLambda_reconstVol_1e-1__NAN/model_060000.pth
distributed   : False

## dataset
eval_dataset : llff_test
eval_scenes  : fern

### TESTING
chunk_size    : 2048
render_stride : 1

## ADDITIONAL
same          : True
num_source_views : 8

 eval_images : True
 eval_rays   : True
 rerun       : True

process_output : True

local_rank : 0
