### INPUT

ckpt_path     : ckpts_test/orig_nan_255000.pth
# ckpt_path                   :  ckpts_test/degae_ablation_255000.pth
# ckpt_path                   :  ckpts_test/degae_preBPN_weightsum_ablation_255000.pth
# ckpt_path                   : ckpts_test/DegAE_AllCondRenderer_preBPN_weightSumFilter_perImg_ftEmbed_embedLoss1e3_200000.pth
distributed                 : False
no_load_opt                 : True
no_load_scheduler           : True
include_target              : True
##
views_attn                  : True
kernel_size                 : [3, 3]
pre_net                     : True
noise_feat                  : True
rgb_weights                 : True

##
degae_feat                  : False #True
weightsum_filtered          : False #True
bpn_prenet                  : False #True
bpn_per_img                 : False #True
cond_renderer               : False #True

## dataset
eval_dataset : llff_test
eval_scenes  : fern

### TESTING
chunk_size    : 2048
render_stride : 1

## ADDITIONAL
same          : True
num_source_views : 8

 eval_images : True
 eval_rays   : True
 rerun       : True

process_output : True

local_rank : 0