### INPUT
expname                     : test #nan_ObjxObj_plain_cleanSrc5 #FullBPN_LatKernelDim16_color1_burst5_wKerLoss_woDetach_latent1e-1
render_stride               : 2  # used in evaluation
distributed                 : False

## dataset
train_dataset               : objaverse #deblur
eval_dataset                : objaverse #
eval_scenes                 : [blurcozy2room] #[fern, orchids, flower, horns, leaves, room, trex, fortress]

### TRAINING
n_iters                     : 255000
N_rand                      : 512
lrate_feature               : 0.001
lrate_mlp                   : 0.0005
lrate_decay_factor          : 0.5
lrate_decay_steps           : 50000
losses                      : [l2, l1, l1_grad, ssim]
losses_weights              : [0,  1,  0,       0]
workers                     : 0

degae_feat                  : False
degae_feat_ckpt             : ./ckpts/0619.pth #./ckpts/model_045000.pth
coarse_feat_dim             : 32
fine_feat_dim               : 32
img_size                    : 256
sum_filtered                : False
bpn_prenet                  : True
ft_embed_fc                 : False
cond_renderer               : False #True
blur_render                 : False
kernel_stack                : True
lambda_latent_loss          : 0.1
lambda_blur_loss            : 0.0
lambda_align_loss           : 0.0
burst_length                : 3
num_source_views            : 5
num_latent                  : 1
center_ratio                : 0.6
channel_upfactor            : 1
basis_dim                   : 16
### TESTING
chunk_size                  : 2048 #2048 # can be biggerd depend on the gpu memory
clean_src_imgs              : False
add_burst_noise             : False

### RENDERING
N_importance                : 64
N_samples                   : 64
inv_uniform                 : True
white_bkgd                  : True

### CONSOLE AND TENSORBOARD
i_img                       : 1500
i_print                     : 100
i_tb                        : 20
i_weights                   : 5000

### additional
#ckpt_path                   : out/NAN/model_255000.pth   # use this if you want to train from a specific checkpoint.
# ckpt_path                   : ./out_deblur/general_DeblurxDeblur_deformBPN_woGroupConv_offsetConv_dim90_src5_src4_includeRGB_LatLoss1e-1_alignLoss1e-1____full__pre__3_3_3__views_attn__l1/model_020000.pth
no_load_opt                 : False
no_load_scheduler           : False
sup_clean                   : True

include_target              : False  # set to False if you want to synthesize images rather than denoise the images
eval_gain                    : [20, 16, 8]
std                         : [-3.0, -0.5, -2.0, -0.5]


views_attn                  : True
kernel_size                 : [3, 3]
pre_net                     : True
noise_feat                  : False
rgb_weights                 : True

local_rank                  : 0