### INPUT
expname                     : nan_targetNov_woGroupConv_blurLoss0_latentLoss1e0_src5_lat3 #nan_revised_targetNov_blurTargetOnly_reconst1e0_woOrig_src5 #nan_targetNov_blurTarget_perImgBasis_src3_lat5_woOrig #nan_targetRef_AnnealReconstLoss1e-2_groupBPN_commonBasis_includeOrig_src3_lat5 #_plainBPN_src8 # 
render_stride               : 2  # used in evaluation
distributed                 : False

## dataset
train_dataset               : deblur_scene
eval_dataset                : deblur_scene_test
# eval_scenes                 : ['blurstair'] #[fern, orchids, flower, horns, leaves, room, trex, fortress]

### TRAINING
n_iters                     : 255000
N_rand                      : 512
lrate_feature               : 0.001
lrate_mlp                   : 0.0005
lrate_decay_factor          : 0.5
lrate_decay_steps           : 50000
losses                      : [l2, l1, l1_grad, ssim]
losses_weights              : [0,  1,  0,       0]
workers                     : 0

degae_feat                  : False
degae_feat_ckpt             : ./ckpts/0619.pth #./ckpts/model_045000.pth
coarse_feat_dim             : 32
fine_feat_dim               : 32
img_size                    : 256
sum_filtered                : True
weightsum_filtered          : False
bpn_prenet                  : True
bpn_per_img                 : True
ft_embed_fc                 : False
cond_renderer               : False
blur_render                 : False
train_scenes                : [blurfactory]
lambda_latent_loss          : 1.0
lambda_blur_loss            : 0.0
num_source_views            : 5
num_latent                  : 3
group_conv                  : False
channel_upfactor            : 2
include_orig                : False
### TESTING
chunk_size                  : 2048 #2048 # can be biggerd depend on the gpu memory
clean_src_imgs              : False


### RENDERING
N_importance                : 64
N_samples                   : 64
inv_uniform                 : True
white_bkgd                  : False

### CONSOLE AND TENSORBOARD
i_img                       : 2500
i_print                     : 100
i_tb                        : 20
i_weights                   : 5000

### additional
#ckpt_path                   : out/NAN/model_255000.pth   # use this if you want to train from a specific checkpoint.
no_load_opt                 : False
no_load_scheduler           : False
sup_clean                   : True

include_target              : False  # set to False if you want to synthesize images rather than denoise the images
eval_gain                    : [20, 16, 8]
std                         : [-3.0, -0.5, -2.0, -0.5]


views_attn                  : True
kernel_size                 : [3, 3]
pre_net                     : True
noise_feat                  : False
rgb_weights                 : True

local_rank                  : 0