### INPUT
expname                     : resUnet_ae_smoothSrcFeat_task24_annealLambda_1e-2_1e-1 #_tvloss_5e-3 #_tvLoss #_woSplit
render_stride               : 2  # used in evaluation
distributed                 : False

## dataset
train_dataset               : llff
eval_dataset                : llff_test
eval_scenes                 : [fern, trex, leaves, horns] # fern, orchids, flower, horns, leaves, room, trex, fortress

### TRAINING
n_iters                     : 255000
N_rand                      : 512
lrate_feature               : 0.001
lrate_mlp                   : 0.0005
lrate_decay_factor          : 0.5
lrate_decay_steps           : 50000
losses                      : [l2, l1, l1_grad, ssim]
losses_weights              : [0,  1,  0,       0]
workers                     : 0

### TESTING
chunk_size                  : 2048 # can be bigger depend on the gpu memory

## AutoEncoder Module
auto_encoder                : True # True
meta_module                 : False
patch_kernel                : False
multiscale                  : False
weighted_reconst            : False
annealing_loss              : True
noisy_src_feature           : False
lambda_reconst_loss         : 0.1
lambda_tv_loss              : 0.0 #5 # 0.01
decoder_lambdas             : [0.01, 0.1]
decoder_tasks               : [2,4]
# decoder 1 | 1. noisy ref img -> clean ref input
# decoder 2 | 2. smooth ref img -> clean ref input
# decoder 3 | 3. noisy src img -> noisy src input
# decoder 4 | 4. smooth src img -> smooth src input


### RENDERING
N_importance                : 64
N_samples                   : 64
inv_uniform                 : True
white_bkgd                  : False

### CONSOLE AND TENSORBOARD
i_img                       : 2500
i_print                     : 100
i_tb                        : 50
i_weights                   : 5000

### additional
#ckpt_path                   : out/NAN/model_255000.pth   # use this if you want to train from a specific checkpoint.
no_load_opt                 : False
no_load_scheduler           : False
sup_clean                   : True

include_target              : True  # set to False if you want to synthesize images rather than denoise the images
eval_gain                    : 16
std                         : [-3.0, -0.5, -2.0, -0.5]


views_attn                  : True
kernel_size                 : [3, 3]
pre_net                     : True
noise_feat                  : True
rgb_weights                 : True

local_rank                  : 0
