### INPUT
expname                     : eval_restormer_nan_src5 #nan_src3_near3_1e-3_1e-2 #_evalNeigh2X_propRange0.75X_src5_near3_L1_1e-1_1e-2 #nan_final_objaverse_reviseTest_woMix_evalNeigh2X_propRange0.75X_src5_near3_L1_1e-1_1e-2 #nan_objv2_revised_src5_near3_smooth1e0_1e-2 #test_rgbd_restormer_expand1.5_BiasFree_nonPixelShuffle_Reconst1e-1 #test_restormer_pretrainPatchMatch_wloss #test_rgbd_detach_feat_stageLoss_1e-1 #test_rgbd_feat_stageLoss #_selfsupervision #nan_ObjxObj_ibrReconst_patchMatch1e0_inputDepthWoBN_base32dim_DetachSrcLatent1_13x13_reconst1e-1 #FullBPN_LatKernelDim16_color1_burst5_wKerLoss_woDetach_latent1e-1
render_stride               : 1  # used in evaluation
distributed                 : False

## dataset
train_dataset               : objaverse  #deblur
eval_dataset                : objaverse_test  #
eval_scenes                 : [blurcozy2room] #[fern, orchids, flower, horns, leaves, room, trex, fortress]

### TRAINING
n_iters                     : 255000
N_rand                      : 512
lrate_feature               : 0.001
lrate_mlp                   : 0.0005
lrate_decay_factor          : 0.5
lrate_decay_steps           : 50000
losses                      : [l2, l1, l1_grad, ssim]
losses_weights              : [0,  1,  0,       0]
workers                     : 0

degae_feat                  : False
degae_feat_ckpt             : ./ckpts/0619.pth #./ckpts/model_045000.pth
coarse_feat_dim             : 32
fine_feat_dim               : 32
img_size                    : 256
burst_length                : 1
num_source_views            : 5
num_latent                  : 1
center_ratio                : 0.6
channel_upfactor            : 1
basis_dim                   : 16
### TESTING
chunk_size                  : 2048 #2048 # can be biggerd depend on the gpu memory
clean_src_imgs              : False
add_burst_noise             : False

### RENDERING
N_importance                : 64
N_samples                   : 64
inv_uniform                 : True
white_bkgd                  : True

### CONSOLE AND TENSORBOARD
i_img                       : 4000
i_print                     : 100
i_tb                        : 20
i_weights                   : 5000

### additional
#ckpt_path                   : out/NAN/model_255000.pth   # use this if you want to train from a specific checkpoint.
# ckpt_path                   :
# ckpt_path                   : ckpts_test/src5_objv2_040000.pth
# ckpt_path                   : out_deblur/test_rgbd_restormer_expand1.5_BiasFree_nonPixelShuffle_Reconst1e-1____full__pre__3_3_3__views_attn__l1/model_065000.pth
# ckpt_path                   : out_deblur/nan_objv2_src5_cleansrc____full__pre__3_3_3__views_attn__l1/model_035000.pth
# ckpt_path                   : /disk1/chanho/3d/MetaNAN/logs_final_save/out/nan_final_objaverse_reviseTest_woMix_plain_src5____full__pre__3_3_3__views_attn__l1/model_255000.pth
# ckpt_path                   : /disk1/chanho/3d/MetaNAN/logs_final_save/out/nan_burst_objaverse_plain_src5____std_-3.0_-1.5_-2.0_-1.25__pre__3_3_3__views_attn__l1/model_255000.pth
# ckpt_path                   : /disk1/chanho/3d/MetaNAN/logs_final_save/out/nan_burst_propRange0.75X_src5_near3_L1_1e-1_1e-2____std_-3.0_-1.5_-2.0_-1.2/model_255000.pth
# ckpt_path                   : /disk1/chanho/3d/MetaNAN/logs_final_save/out/nan_final_objaverse_reviseTest_woMix_propRange0.75X_src5_near3_L1_1e-1_1e-2____full__pre__3_3_3__views_attn__l1/model_255000.pth
# clean_ckpt_path             : /disk1/chanho/3d/MetaNAN/logs_final_save/out/nan_burst_objaverse_plain_src5____std_-3.0_-1.5_-2.0_-1.25__pre__3_3_3__views_attn__l1/model_255000.pth
restormer_ckpt_path         : /disk1/chanho/3d/MetaNAN/logs_final_save/restormer_blur.pth
ckpt_path                   : /disk1/chanho/3d/MetaNAN/logs_final_save/nan_clean_plain_src5.pth
# ckpt_path                   : /disk1/chanho/3d/MetaNAN/logs_final_save/nan_objaverse_src3.pth
eval_mode                   : False

no_load_opt                 : False
no_load_scheduler           : False
sup_clean                   : True

include_target              : False  # set to False if you want to synthesize images rather than denoise the images
eval_gain                    : [20, 16, 8]
std                         : [-3.0, -0.5, -2.0, -0.5]
# std                         : [-3.0, -1.5, -2.0, -1.25]


views_attn                  : True
kernel_size                 : [3, 3]
pre_net                     : True
noise_feat                  : False
rgb_weights                 : True

local_rank                  : 0


        # parser.add_argument('--eval_mode', default=False, action="store_true")
        # parser.add_argument('--restormer_ckpt_path', default=False, action="store_true")
        # parser.add_argument("--clean_ckpt_path", type=str, default=None)
        # parser.add_argument('--calc_depth_var', default=False, action="store_true")

